name: Simão Seiça Web Site
markdown: redcarpet
safe: true
lsi: false
pygments: true
auto: true
server: true
exclude:
- README.md
- Rakefile
lsi: false
pygments: true
permalink: pretty
url: http://simaoseica.pt
exclude:
- README.md
- Rakefile

#Dev
auto: true
#server: true
